on:
  rss:
    url: https://github.com/LuisAlejandro/dockershelf/releases.atom
    config:
      limit: 1
jobs:
  dockershelf:
    name: Publish new Dockershelf versions
    runs-on: ubuntu-20.04
    steps:
      - name: Post tweet
        uses: LuisAlejandro/send-tweet-with-media@0.2.0
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_OAUTH_TOKEN: ${{ secrets.TWITTER_OAUTH_TOKEN }}
          TWITTER_OAUTH_SECRET: ${{ secrets.TWITTER_OAUTH_SECRET }}
          STATUS_TEXT: "${{ on.rss.outputs.title }}: A new version of #dockershelf has been released! ${{ on.rss.outputs.link }}"
          STATUS_IMAGE_URL_1: https://user-images.githubusercontent.com/324683/95548254-ae7ad600-09d2-11eb-87c2-82f6dc65bb32.png
